#ifndef PLANTOUR_H
#define PLANTOUR_H

#include <QWidget>

namespace Ui {
class plantour;
}

/**
 * @class plantour
 * @brief Provides functionality for planning and analyzing trips between MLB stadiums.
 *
 * This class allows users to plan various types of stadium trips such as Dijkstra-optimized routes,
 * minimum spanning trees, DFS/BFS traversals, and custom greedy paths.
 */
class plantour : public QWidget
{
    Q_OBJECT

public:
    /**
     * @brief Constructs the plantour widget.
     * @param parent Optional parent widget.
     */
    explicit plantour(QWidget *parent = nullptr);

    /**
     * @brief Destroys the plantour widget.
     */
    ~plantour();

private slots:
    /**
     * @brief Closes the plantour window.
     */
    void on_pb_exit_clicked();

    /**
     * @brief Plans a trip starting from Dodger Stadium using Dijkstra's optimized route.
     */
    void on_pb_team_details_clicked();

    /**
     * @brief Plans a custom trip based on user-selected stadiums using a greedy route.
     */
    void on_pb_team_report_clicked();

    /**
     * @brief Displays the MST (Minimum Spanning Tree) of all stadiums using Kruskal's algorithm.
     */
    void on_pb_maintenance_clicked();

    /**
     * @brief Executes a DFS (Depth-First Search) traversal starting from Oracle Park.
     */
    void on_pushButton_clicked();

    /**
     * @brief Executes a BFS (Breadth-First Search) traversal starting from Target Field.
     */
    void on_pushButton_2_clicked();

    /**
     * @brief Allows user to define a custom trip through selected stadiums.
     */
    void on_pb_plan_vacation_clicked();

    /**
     * @brief Plans a full trip to visit all stadiums starting from Marlins Park.
     */
    void on_pb_stadium_report_clicked();

private:
    Ui::plantour *ui; ///< Pointer to the UI elements generated by Qt Designer.
};

#endif // PLANTOUR_H
