name: Build Qt CS1D C++ Project 2 Baseball

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Qt (Windows - MinGW)
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.5.2"
          host: windows
          target: desktop
          arch: win64_mingw81
          archives: 'qttools qtsvg qtbase'
          install-deps: true

      - name: Install CMake (Windows/macOS)
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install Doxygen
        run: choco install doxygen.install -y
        shell: powershell

      - name: Add Doxygen to PATH
        run: |
          echo "C:\Program Files\doxygen\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: powershell

      - name: Verify Doxygen Installation
        run: doxygen --version
        shell: cmd

      - name: Configure project
        run: cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

      - name: Build project
        run: cmake --build ${{ env.BUILD_DIR }} --parallel

      - name: (Optional) Run tests
        run: |
          if [ -f "${{ env.BUILD_DIR }}/tests/my_tests" ]; then
            ${{ env.BUILD_DIR }}/tests/my_tests
          fi
        shell: bash

      - name: Generate Documentation with Doxygen
        run: doxygen Doxyfile
        shell: cmd

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Doxygen-Docs
          path: docs/html

      - name: Create Windows Artifact
        run: |
          mkdir windows_build
          copy build\release\college.exe windows_build\
          7z a college-Windows.zip windows_build\*
        shell: cmd

      - uses: actions/upload-artifact@v4
        with:
          name: college-Windows
          path: college-Windows.zip


