name: Build Qt CS1D C++ Project 2 Baseball

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_DIR: ${{ github.workspace }}\build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Qt (Windows - MinGW)
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.6.2' # Use a known working version
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          archives: 'qtbase qttools qtsvg'
          install-deps: true

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Add MinGW to PATH
        run: echo "${{ env.Qt6_DIR }}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: powershell

      - name: Install Doxygen
        run: choco install doxygen.install -y
        shell: powershell

      - name: Add Doxygen to PATH
        run: echo "C:\Program Files\doxygen\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: powershell

      - name: Verify Doxygen Installation
        run: doxygen --version
        shell: cmd

      - name: Configure project with MinGW Makefiles
        run: cmake -S . -B "${{ env.BUILD_DIR }}" -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

      - name: Build project
        run: cmake --build "${{ env.BUILD_DIR }}" --parallel

      - name: Add MinGW to PATH
        run: echo "${{ env.Qt6_DIR }}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: powershell
  
      - name: (Optional) Run tests
        run: |
          if exist "${{ env.BUILD_DIR }}\baseball_tests.exe" (
            "${{ env.BUILD_DIR }}\baseball_tests.exe"
          )
        shell: cmd

      - name: Generate Documentation with Doxygen
        run: doxygen Doxyfile
        shell: cmd

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Doxygen-Docs
          path: docs/html

      - name: Create Windows Artifact
        run: |
          mkdir windows_build
          copy build\release\college.exe windows_build\
          7z a college-Windows.zip windows_build\*
        shell: cmd

      - name: Upload Executable Zip
        uses: actions/upload-artifact@v4
        with:
          name: college-Windows
          path: college-Windows.zip
